# Site settings
title: Salman ElDash
email: salman@eldash.info
description: > # this means to ignore newlines until "baseurl:"
  Salman ElDash . You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/portfolio" # the subpath of your site, e.g. /blog/
url: "http://salman19.github.io" # the base hostname & protocol for your site
twitter_username: salmaneldash
github_username:  salman19

# Build settings
markdown: kramdown
